[package]
name = "ch15_scoping_rules"
version = "0.1.0"
authors = ["hongry"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
