[package]
name = "ch03-separate-modules-into-files"
version = "0.1.0"
authors = ["hongry"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"